'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
const googleErrors:Record<string,string>={'google-unavailable':'Google sign-in is not available yet. Please use email and password.','google-cancelled':'Google sign-in was cancelled or expired. Please try again.','google-failed':'Google sign-in could not finish. Please try again.','use-password':'This email already has a password account. Please sign in with your password.','try-later':'Too many attempts. Please try again later.'};
export function AuthForm({mode}:{mode:'sign-in'|'sign-up'}){
 const signup=mode==='sign-up';const [error,setError]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[google,setGoogle]=useState<boolean|null>(null);
 useEffect(()=>{const code=new URLSearchParams(window.location.search).get('error');void fetch('/api/auth/config',{cache:'no-store'}).then(r=>r.json() as Promise<{googleAvailable?:boolean}>).then(v=>{setGoogle(v.googleAvailable===true);if(code)setError(googleErrors[code]||'Please try signing in again.');}).catch(()=>setGoogle(false));},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),email:data.get('email'),password:data.get('password')})});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||'Please try again.');return;}window.location.assign('/account');}catch{setError('We could not connect. Please try again.');}finally{setBusy(false);}}
 return <section className="auth-card" aria-label={signup?'Create your account':'Sign in to your account'}><p className="eyebrow">Your learning space</p><h1>{signup?'Join Girls Beyond Gravity':'Welcome back'}</h1><p>{signup?'Create an account to keep your learning journey connected.':'Sign in and continue exploring physics with us.'}</p>
 <button className="button auth-google" type="button" disabled={google!==true||busy} onClick={()=>window.location.assign('/api/auth/google')}><span aria-hidden="true" className="google-letter">G</span>Continue with Google</button>{google===false&&<p className="auth-note">Google sign-in is coming soon. You can use email and password now.</p>}
 <div className="auth-divider"><span>or use your email</span></div>
 <form onSubmit={submit} className="auth-form">{signup&&<label htmlFor="auth-name">Name<input id="auth-name" name="name" autoComplete="name" required maxLength={80} disabled={busy}/></label>}
 <label htmlFor="auth-email">Email<input id="auth-email" name="email" type="email" autoComplete="email" placeholder="you@example.com" maxLength={254} required disabled={busy}/></label>
 <label htmlFor="auth-password">Password<span className="auth-password"><input id="auth-password" name="password" type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} minLength={signup?12:undefined} maxLength={72} aria-describedby={signup?'password-help':undefined} required disabled={busy}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Hide password':'Show password'} aria-pressed={show}>{show?'Hide':'Show'}</button></span></label>
 {signup&&<p id="password-help" className="auth-note">Use at least 12 characters. A memorable phrase works well.</p>}{error&&<p className="auth-error" role="alert">{error}</p>}<button className="button primary" type="submit" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form>
 <p className="auth-switch">{signup?'Already have an account?':'New to Girls Beyond Gravity?'} <Link href={signup?'/sign-in':'/sign-up'}>{signup?'Sign in':'Create an account'}</Link></p></section>;
}
