import {OfficialQuestionViewer} from "./OfficialQuestionViewer";
import {PhysicsText} from './PhysicsText';
const p1='https://apcentral.collegeboard.org/media/pdf/ap-physics-1-course-and-exam-description.pdf';
const p2='https://apcentral.collegeboard.org/media/pdf/ap-physics-2-course-and-exam-description.pdf';
type Resource={title:string;url:string;pages:number[];task:string;after:string};
const resources:Record<string,Resource[]>={
 '2.2':[{title:'Official sample MCQ 2 — force diagrams and velocity graphs',url:`${p1}#page=184`,pages:[184,185],task:'Attempt sample MCQ 2 on printed pages 177–178. Read the velocity-component slopes, then choose the compatible force diagram.',after:'Find the sign of acceleration from each velocity–time slope, then compare those signs with the net components in the candidate FBDs. Velocity direction alone does not identify net force.'}],
 '2.5':[{title:'Official sample MCQ 1 — equilibrium of connected blocks',url:`${p1}#page=183`,pages:[183],task:'Attempt sample MCQ 1 on printed page 176. Make a separate FBD for each relevant block before comparing the given choices.',after:'Start with the hanging block in equilibrium, which determines string tension. Then balance the horizontal forces on the supported block. The contact force must balance that tension; do not insert total system mass into an acceleration formula when acceleration is zero.'}],
 '2.9':[{title:'2024 released FRQ 1(c) — forces at the top of a loop',url:'https://apcentral.collegeboard.org/media/pdf/ap24-frq-physics-1.pdf#page=6',pages:[4,6],task:'Attempt part (c)(i) after this lesson. Parts (a), (b), and (c)(ii) also require Unit 3 energy ideas, so return to the complete question after learning energy conservation.',after:'At the top, inward is downward. Include only actual interactions and write their inward sum as mv²/R. If contact would require a negative normal force, the assumed contact is impossible.'}],
 '9.1':[{title:'Official sample MCQ 1 — root-mean-square speed',url:`${p2}#page=195`,pages:[195],task:'Attempt sample MCQ 1 on printed page 188. Use the relationship between rms speed squared and absolute temperature. The official answer table follows the sample questions in the same document.',after:'For a fixed particle mass, T₂/T₁ = (v_rms,2/v_rms,1)². A doubling of rms speed multiplies kelvin temperature by four. Explain the square using kinetic energy rather than memorizing an answer.'}],
 '9.2':[{title:'2025 released FRQ 2 (Version J) — piston and gas states',url:'https://apcentral.collegeboard.org/media/pdf/ap25-frq-physics-2.pdf#page=6',pages:[6,7],task:'Attempt the pressure and state reasoning in Question 2. Combine a piston FBD with the gas law and interpret the bath constraint before drawing the P–V path.',after:'A stationary piston requires the upward gas-pressure force to balance atmospheric pressure and the load. A slow change in contact with a fixed-temperature bath is approximately isothermal. A greater load raises equilibrium pressure; compare endpoint PV products when considering a different bath temperature.'}],
 '9.4':[{title:'2025 released FRQ 2 (Version J) — graph the compression path',url:'https://apcentral.collegeboard.org/media/pdf/ap25-frq-physics-2.pdf#page=7',pages:[6,7],task:'Revisit part C after the first-law lesson. Draw the process arrow and state the signs of work by and work on the gas. These sign checks are additional site practice, not extra official parts.',after:'For slow compression at fixed bath temperature, the gas follows an isotherm toward smaller volume and greater pressure. Work by the gas is negative and work on it positive. For the ideal-gas isothermal change, ΔU = 0, so it releases heat.'}],
 '9.5':[{title:'2026 released FRQ 1 (Version J) — gas heating and specific heat',url:'https://apcentral.collegeboard.org/media/pdf/ap26-frq-physics-2.pdf#page=3',pages:[3,4],task:'Attempt Question 1 after Topics 9.1–9.5. It connects a speed-distribution sketch, gas-state algebra, thermal equilibrium, and heat-capacity reasoning.',after:'At fixed amount and volume, pressure ratios give kelvin-temperature ratios. Use the gas-law temperature change in Q = mcΔT for the small solid, and distinguish mean particle energy from the shape of the speed distribution. For the mixing comparison, equal transferred energy produces a larger temperature change for smaller heat capacity.'}]
};
export function ReleasedPractice({topic,course}:{topic?:string;course?:'physics-1'|'physics-2'}) {
 const selected=topic?resources[topic]:Object.entries(resources).filter(([key])=>key.startsWith(course==='physics-1'?'2.':'9.')).flatMap(([,r])=>r);
 if(!selected?.length)return null;
 const subject=course??(topic?.startsWith('2.')?'physics-1':'physics-2');
 return <section className="lesson-section official-practice-section"><h2>Real College Board questions</h2><p>Attempt these after the original practice. Read the official question pages below, including the original figures. The preparation and discussion below are written by Girls Beyond Gravity.</p>{selected.map(r=><article className="official-ap-practice" key={r.title}><small>Verified public College Board source</small><h3>{r.title}</h3><p>{r.task}</p><OfficialQuestionViewer url={r.url} title={r.title} pages={r.pages}/><a className="button secondary" href={r.url} target="_blank" rel="noreferrer">Open full-size source</a><details><summary>After attempting: discuss the physics</summary><p><PhysicsText text={r.after}/></p></details></article>)}<p><a href={`https://apcentral.collegeboard.org/courses/ap-${subject}/exam/past-exam-questions`} target="_blank" rel="noreferrer">Released past papers, scoring guidelines, and sample responses</a>. Use official scoring guidance to assess your written work. Earlier papers can include content and formats from before the course revisions.</p><p>These public sample MCQs are genuine College Board questions. The site’s quizzes are original AP-style practice; secure AP Classroom questions are accessed through an authorized teacher and are not reproduced here.</p></section>;
}
