'use client';
import {useState,type ReactNode} from 'react';
import {gasPressureKPa,speedDensity,heatingState,equilibriumTemperatures} from '@/lib/thermalModels';
function Plot({label,xLabel,yLabel,xMax,yMin=0,yMax,xTicks,yTicks,children}:{label:string;xLabel:string;yLabel:string;xMax:number;yMin?:number;yMax:number;xTicks:number[];yTicks:number[];children:(x:(v:number)=>number,y:(v:number)=>number)=>ReactNode}) {
 const x=(v:number)=>80+v/xMax*490;const y=(v:number)=>280-(v-yMin)/(yMax-yMin)*210;
 return <svg viewBox="0 0 640 350" role="img" aria-label={label}><path d="M80 60V280H580" fill="none" stroke="#646171" strokeWidth="1.5"/><text x="80" y="35">{yLabel}</text><text x="330" y="339" textAnchor="middle">{xLabel}</text>{yTicks.map(v=><g key={v}><line x1="80" x2="570" y1={y(v)} y2={y(v)} stroke="#e5e0eb"/><text x="69" y={y(v)+5} textAnchor="end">{v}</text></g>)}{xTicks.map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1="280" y2="286" stroke="#646171"/><text x={x(v)} y="306" textAnchor="middle">{v}</text></g>)}{children(x,y)}</svg>;
}
const line=(points:string,color='#625780')=><polyline points={points} fill="none" stroke={color} strokeWidth="2.5"/>;
export function ThermalTopicExplorer({topic}:{topic:string}) {
 const [temperature,setTemperature]=useState(300);const [volume,setVolume]=useState(5);const [graph,setGraph]=useState('pv');const [time,setTime]=useState(10);const [path,setPath]=useState('constant');const [energy,setEnergy]=useState(20);const [heat,setHeat]=useState(800);const [efficiency,setEfficiency]=useState(0.375);
 const input=(label:string,value:number,set:(v:number)=>void,min:number,max:number,step:number,unit:string)=><label>{label}: {value} {unit}<input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>set(+e.target.value)}/></label>;
 let content:ReactNode;
 if(topic==='9.1')content=<>{input('Comparison temperature',temperature,setTemperature,200,600,10,'K')}<p>Same helium atoms and same particle count. Reference: 300 K (purple); comparison: {temperature} K (green). The full probability density integrates to 1.</p><Plot label="Normalized Maxwell–Boltzmann speed distributions for helium at 300 kelvin and the selected temperature" xLabel="Speed (m/s)" yLabel="Probability density [1/(m/s)]" xMax={6000} yMax={0.0013} xTicks={[0,1500,3000,4500,6000]} yTicks={[0,0.0005,0.001]}>{(x,y)=><>{line(Array.from({length:201},(_,i)=>`${x(i*30).toFixed(3)},${y(speedDensity(i*30,300)).toFixed(3)}`).join(' '))}{line(Array.from({length:201},(_,i)=>`${x(i*30).toFixed(3)},${y(speedDensity(i*30,temperature)).toFixed(3)}`).join(' '),'#476f62')}</>}</Plot><p role="status">Comparison v_rms = {Math.sqrt(3*1.380649e-23*temperature/6.64e-27).toFixed(0)} m/s. The plotted peak is the most probable speed, not v_rms.</p><p>Predict how the peak and width change before moving the slider. Explain why the area stays the same.</p></>;
 else if(topic==='9.2')content=<>{input('Temperature',temperature,setTemperature,200,600,10,'K')}{input('Volume',volume,setVolume,2,10,0.5,'L')}<label>Graph relationship<select aria-label="Graph relationship" value={graph} onChange={e=>setGraph(e.target.value)}><option value="pv">Pressure versus volume — fixed T</option><option value="pt">Pressure versus temperature — fixed V</option><option value="inverse">Pressure versus inverse volume — fixed T</option></select></label><Plot label={`Ideal-gas ${graph==='pv'?'pressure versus volume':graph==='pt'?'pressure versus temperature':'pressure versus inverse volume'} graph for 0.20 mol`} xLabel={graph==='pv'?'Volume (L)':graph==='pt'?'Temperature (K)':'Inverse volume (L⁻¹)'} yLabel="Pressure (kPa)" xMax={graph==='pv'?10:graph==='pt'?600:0.5} yMax={500} xTicks={graph==='pv'?[0,2,4,6,8,10]:graph==='pt'?[0,150,300,450,600]:[0,0.1,0.2,0.3,0.4,0.5]} yTicks={[0,100,200,300,400,500]}>{(x,y)=>{const points=Array.from({length:101},(_,i)=>{const a=graph==='pv'?2+i*0.08:graph==='pt'?i*6:i*0.005;const p=graph==='pv'?gasPressureKPa(temperature,a):graph==='pt'?gasPressureKPa(a,volume):0.2*8.314*temperature*a;return `${x(a)},${y(p)}`;}).join(' ');const markerX=graph==='pv'?volume:graph==='pt'?temperature:1/volume;return <>{line(points)}<circle cx={x(markerX)} cy={y(gasPressureKPa(temperature,volume))} r="5" fill="#96674b"/></>;}}</Plot><p role="status">0.20 mol at {temperature} K and {volume.toFixed(1)} L: P = {gasPressureKPa(temperature,volume).toFixed(1)} kPa absolute.</p><p>{graph==='pv'?'The curve starts at 2 L; the ideal pressure diverges as V approaches zero. Each curve keeps T fixed.':graph==='pt'?'The line has slope nR/V. Its extension to 0 K is an ideal-model extrapolation, not a claim that a real gas stays gaseous there.':'The straight line has slope nRT. Inverse volume has units L⁻¹; it is not volume.'}</p></>;
 else if(topic==='9.3'){const state=equilibriumTemperatures(time);content=<>{input('Elapsed time',time,setTime,0,60,1,'s')}<Plot label="Temperatures of two insulated bodies approaching equilibrium with unequal heat capacities" xLabel="Time (s)" yLabel="Temperature (°C)" xMax={60} yMax={100} xTicks={[0,15,30,45,60]} yTicks={[0,20,40,60,80,100]}>{(x,y)=><>{line(Array.from({length:121},(_,i)=>`${x(i/2)},${y(equilibriumTemperatures(i/2).hot)}`).join(' '),'#96674b')}{line(Array.from({length:121},(_,i)=>`${x(i/2)},${y(equilibriumTemperatures(i/2).cold)}`).join(' '),'#476f62')}<circle cx={x(time)} cy={y(state.hot)} r="5" fill="#96674b"/><circle cx={x(time)} cy={y(state.cold)} r="5" fill="#476f62"/></>}</Plot><p role="status">Hot body (brown): {state.hot.toFixed(1)} °C; cold body (green): {state.cold.toFixed(1)} °C. Equilibrium limit: 40 °C.</p><p>Model: hot heat capacity 200 J/K; cold heat capacity 400 J/K; constant thermal conductance between bodies; no external losses. The hot body’s temperature falls twice as far because its heat capacity is half as large. At every time, energy lost by one equals energy gained by the other.</p></>;}
 else if(topic==='9.4'){const constant=path==='constant';const work=constant?300:path==='high'?400:200;const du=constant?450:900;content=<><label>Specified process<select aria-label="Specified process" value={path} onChange={e=>setPath(e.target.value)}><option value="constant">Constant 100 kPa: 2 → 5 L</option><option value="high">A → B: heat first, then expand at 200 kPa</option><option value="low">A → B: expand at 100 kPa, then heat</option></select></label><Plot label="Specified pressure–volume path with shaded positive expansion work" xLabel="Volume (L)" yLabel="Pressure (kPa)" xMax={6} yMax={300} xTicks={[0,1,2,3,4,5,6]} yTicks={[0,100,200,300]}>{(x,y)=>{const end=constant?5:4;const p=path==='high'?200:100;return <><rect x={x(2)} y={y(p)} width={x(end)-x(2)} height={y(0)-y(p)} fill="#dbe8df"/>{line(constant?`${x(2)},${y(100)} ${x(5)},${y(100)}`:path==='high'?`${x(2)},${y(100)} ${x(2)},${y(200)} ${x(4)},${y(200)}`:`${x(2)},${y(100)} ${x(4)},${y(100)} ${x(4)},${y(200)}`)}<circle cx={x(2)} cy={y(100)} r="5" fill="#625780"/><text x={x(2)-15} y={y(100)+24}>A</text><circle cx={x(end)} cy={y(constant?100:200)} r="5" fill="#96674b"/><text x={x(end)+12} y={y(constant?100:200)-10}>B</text><text x={x((2+end)/2)} y={y(p)+35} textAnchor="middle">Expansion →</text></>;}}</Plot><p role="status">A → B: W_by = +{work} J; ΔU = +{du} J; Q = +{work+du} J (monatomic ideal gas).</p><p>Only horizontal legs change volume. Shade from P = 0 to the expansion path to calculate work. Compare the two A → B paths: endpoint ΔU agrees, but work and heat differ.</p></>;}
 else if(topic==='9.5'){const state=heatingState(energy);content=<>{input('Energy added',energy,setEnergy,0,58.5,0.1,'kJ')}<Plot label="Quantitative heating curve for 0.10 kg of ice from minus 20 Celsius through melting to warming liquid water" xLabel="Energy added (kJ)" yLabel="Temperature (°C)" xMax={60} yMin={-20} yMax={60} xTicks={[0,10,20,30,40,50,60]} yTicks={[-20,0,20,40,60]}>{(x,y)=><>{line([0,4.2,37.6,58.5].map(q=>`${x(q)},${y(heatingState(q).temperature)}`).join(' '))}<circle cx={x(energy)} cy={y(state.temperature)} r="5" fill="#96674b"/><text x={x(20)} y={y(0)-15} textAnchor="middle">Melting at 0 °C</text></>}</Plot><p role="status">{state.phase}: {state.temperature.toFixed(1)} °C; melted fraction {(state.meltedFraction*100).toFixed(1)}%.</p><p>At 4.2 kJ melting starts; at 37.6 kJ it finishes. The curve stops at 50 °C and does not include boiling. Predict which formula applies before choosing an energy value.</p></>;}
 else content=<>{input('Heat absorbed per cycle',heat,setHeat,400,1200,20,'J')}{input('Efficiency',efficiency,setEfficiency,0.1,0.5,0.025,'(fraction)')}<svg viewBox="0 0 640 330" role="img" aria-label="Cyclic heat-engine energy flow with absorbed heat, work output, and rejected heat"><rect x="190" y="20" width="240" height="48" rx="10" fill="#f0e4d7"/><text x="310" y="51" textAnchor="middle">Hot reservoir</text><rect x="210" y="125" width="200" height="65" rx="10" fill="#ece6f3"/><text x="310" y="165" textAnchor="middle">Cyclic engine</text><rect x="190" y="260" width="240" height="48" rx="10" fill="#e7eee8"/><text x="310" y="290" textAnchor="middle">Cold reservoir</text><path d="M310 68V122M310 190V257M410 157H530" stroke="#625780" strokeWidth="2" fill="none"/><path d="M305 114L310 122L315 114M305 249L310 257L315 249M522 152L530 157L522 162" stroke="#625780" strokeWidth="2" fill="none"/><text x="326" y="100">Q_H = {heat} J</text><text x="326" y="230">Q_C = {(heat*(1-efficiency)).toFixed(0)} J</text><text x="440" y="140">W = {(heat*efficiency).toFixed(0)} J</text></svg><p role="status">η = {(efficiency*100).toFixed(1)}%; work = {(heat*efficiency).toFixed(0)} J; rejected heat = {(heat*(1-efficiency)).toFixed(0)} J.</p><p>This explorer illustrates cycle energy accounting, not a prediction of achievable efficiency for unspecified reservoirs. The selected range is illustrative. Arrows show transfer direction, not a quantitative width scale.</p></>;
 return <section className="lesson-lab" aria-label="Interactive concept explorer"><h3>Predict, explore, explain</h3>{content}</section>;
}
