export const dynamicsGlossary:Record<string,string>={
'system':'The object or collection selected for analysis.',surroundings:'Everything outside the selected system.', 'system boundary':'An imagined boundary separating included objects from their surroundings.', 'internal interaction':'An interaction between included parts of a system.', 'external interaction':'An interaction between the system and an outside object.', 'center of mass':'The mass-weighted average position of a system.',
force:'An interaction that can change motion; measured in newtons.',interaction:'A mutual influence between two objects.', 'free-body diagram':'A representation of all external forces acting on one selected object or system.', 'normal force':'Contact force perpendicular to a surface.', tension:'Pull along a taut string or cable.',friction:'Contact force parallel to a surface opposing sliding or its tendency.',weight:'Gravitational force on an object.', 'net force':'The vector sum of external forces on the selected system.',
'interaction pair':'Equal and opposite forces of the same interaction acting on different objects.',"Newton's third law":'Each interaction gives equal-magnitude opposite-direction forces on the two participants.', 'force of A on B':'Force whose source is A and receiver is B.', 'force of B on A':'The partner force whose source is B and receiver is A.', 'equal magnitude':'The same positive force size, even if vector directions differ.', 'opposite direction':'Directions separated by 180° along the interaction line.',
inertia:'Resistance to a change of velocity, measured by mass.',equilibrium:'Zero net force and unchanged velocity in an inertial frame.', 'constant velocity':'Unchanging speed and direction.', 'inertial reference frame':'A reference frame in which an isolated object has constant velocity.', mass:'Measure of inertia, in kg.',acceleration:'Rate of change of velocity, in m/s².', 'connected system':'Objects linked by contact, a string, or another interaction with stated motion constraints.', 'force-acceleration graph':'A graph relating net force and acceleration; its slope depends on which quantity is vertical.',
'universal gravitation':'Attraction between masses proportional to their product and inversely proportional to squared separation.', 'gravitational field':'Gravitational force per unit test mass at a point; N/kg.', 'apparent weight':'The support force measured by a scale.', 'free fall':'Motion under gravity alone, with drag and support forces negligible.', 'inverse square':'Dependence proportional to 1/r².',
'static friction':'Friction when contact surfaces do not slide relative to one another.', 'kinetic friction':'Friction during relative sliding.', 'coefficient of friction':'A dimensionless parameter relating friction to normal force in the dry-contact model.', 'maximum static friction':'The largest available static friction, μ_s N.', 'relative motion':'Motion described compared with another object or frame.',
'spring force':'Elastic force produced by spring deformation.', 'restoring force':'Force directed toward an equilibrium or relaxed configuration.', 'relaxed length':'Spring length with no elastic deformation.', 'spring constant':'Stiffness k, measured in N/m.',stretch:'Extension beyond relaxed length.',compression:'Reduction below relaxed length.',"Hooke's law":'Linear restoring force F_s,x = −kx within the elastic range.',
'circular motion':'Motion along a circular path.', 'tangential velocity':'Velocity directed along the tangent to the path.', 'centripetal acceleration':'Inward radial acceleration v²/r.', 'inward net force':'The sum of real force components toward the centre.',period:'Time for one complete revolution, in s.',frequency:'Revolutions per second, in Hz.',orbit:'Motion around a gravitating source, maintained by gravitational acceleration.', 'banked curve':'A tilted turn where normal force can contribute an inward horizontal component.'
};
