import {guidedLessons} from "./guidedLessons";
export type Check = { prompt: string; answer: string; hint: string };
export type Lesson = { slug: string; title: string; apTopic: string; estimatedTime: string; status: string; summary: string; vocabulary: string[]; equations: string[]; concept: string; example: string; mistake: string; objectives: string[]; terms: [string, string][]; sections: { title: string; text: string }[]; worked: { prompt: string; steps: string[] }[]; checks: Check[]; lab: 'thermal' | 'motion' | 'field'; labNote: string };
export type Question = { prompt: string; choices: string[]; correct: number; explanation: string };
export type UnitOne = { slug: string; title: string; apNumber: number; source: string; description: string; status: string; progress: string; objectives: string[]; lessons: Lesson[]; practice: Check[]; testStatus: string; questions: Question[]; freeResponse: { prompt: string; rubric: string[] }[] };
function lesson(apTopic: string, title: string, summary: string, terms: [string,string][], equations: string[], sections: {title:string;text:string}[], worked: {prompt:string;steps:string[]}[], mistake: string, checks: Check[], lab: Lesson['lab'], labNote: string): Lesson {
 return { apTopic, title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''), summary, terms, vocabulary: terms.map(t=>t[0]), equations, sections, worked, concept: sections[0].text, example: worked[0].prompt, mistake, checks, lab, labNote, objectives: [summary, 'Represent the situation, state assumptions, and justify your result with units.'], estimatedTime:'45–65 minutes', status:'Available' };
}
const s=(title:string,text:string)=>({title,text});
const w=(prompt:string,...steps:string[])=>({prompt,steps});
const c=(prompt:string,answer:string,hint:string)=>({prompt,answer,hint});
const q=(prompt:string,choices:string[],correct:number,explanation:string)=>({prompt,choices,correct,explanation});
const thermal: Lesson[] = [
 lesson('9.1','Kinetic Theory of Temperature and Pressure','Connect microscopic particle motion to temperature and gas pressure.',[
 ['Temperature','A measure related to the average translational kinetic energy of gas particles; SI unit kelvin (K).'],['Pressure','Normal force per area, measured in pascals (Pa = N/m²).'],['Internal energy','Energy stored in the microscopic motions and interactions of a system.'],['Absolute zero','0 K, the lower limit of thermodynamic temperature; not a claim that all quantum motion vanishes.']],
 ['T(K) = T(°C) + 273.15','K_avg = (3/2)k_B T','PV = (2/3)N K_avg','P = F_perpendicular / A','k_B = 1.38 × 10⁻²³ J/K','N: particle count; K_avg: average translational kinetic energy per particle'],[
 s('From particles to pressure','Gas particles move randomly. Collisions with a container wall change particle momentum; the wall receives impulses. Their average force over a wall area produces pressure. More particles per volume or greater average particle speed produces greater pressure.'),
 s('What temperature tells you','For a classical ideal gas, average translational kinetic energy depends only on absolute temperature, not molecular mass. At the same temperature, lighter molecules have higher typical speeds than heavier molecules. Temperature is not the total energy: twice as many identical particles at the same temperature store twice the translational kinetic energy.'),
 s('Choosing a model','An ideal gas neglects molecular volume and interparticle forces except in collisions. It approximates dilute gases away from condensation. Internal energy of a monatomic ideal gas is only translational kinetic energy, U = (3/2)Nk_B T. Molecules with rotational or vibrational energy can have more internal energy at the same temperature.')],
 [w('How does average translational kinetic energy change from 300 K to 450 K?','Use K_avg ∝ T with temperatures in kelvin.','K_final/K_initial = 450/300 = 1.50.','Each particle has 50% more average translational kinetic energy, regardless of molecular mass.'),w('A gas exerts 240 N normally over 0.020 m². Find pressure.','P = F/A = 240/0.020.','P = 12,000 Pa = 12 kPa. This is force per area, not an energy.')],
 'Do not compare temperature ratios in Celsius or equate equal temperature with equal particle speed.',
 [c('Helium and neon are at the same temperature. Which has greater average translational kinetic energy?','They are equal. Helium atoms have greater typical speeds because their mass is smaller.','Separate energy from speed.'),c('A sealed rigid gas container is heated. Explain the pressure increase.','Faster particles transfer more momentum to the walls per unit time. With fixed particle count and volume, P increases in proportion to T.','Think about wall impulses.')], 'thermal','The explorer models a fixed amount of monatomic ideal gas. At fixed volume, compare pressure as you change temperature.'),
 lesson('9.2','The Ideal Gas Law','Relate gas pressure, volume, amount, and absolute temperature.',[
 ['Mole','An amount containing N_A = 6.022 × 10²³ particles.'],['Volume','Space occupied by the gas; use cubic metres (m³).'],['Absolute pressure','Pressure measured relative to a vacuum; gauge pressure must have atmospheric pressure added.'],['State variable','A quantity describing the equilibrium state, such as P, V, or T.']],
 ['PV = nRT = Nk_B T','R = 8.314 J/(mol·K)','P₁V₁/T₁ = P₂V₂/T₂ (fixed amount)','n: amount in mol; N: particle count; P: absolute pressure; V: volume; T: absolute temperature'],[
 s('Count particles consistently','n is the number of moles and N is the number of particles. Choose nR or Nk_B; never mix their constants. Pressure is absolute pressure, volume is in m³, and temperature is in K. One litre is 10⁻³ m³.'),
 s('Hold one variable fixed','For fixed amount, an isothermal change has constant T and PV constant. An isochoric change has constant V and P/T constant. An isobaric change has constant P and V/T constant. These are constraints; identify the physical constraint before doing algebra.'),
 s('Reason with ratios','On a P–V graph, constant-temperature states lie on a descending hyperbola. A higher-temperature isotherm lies above a lower-temperature one for the same gas amount. The ideal gas law links states, but does not by itself tell you how much heat or work a process transfers.')],
 [w('Find pressure for 0.20 mol at 300 K in 0.0050 m³.','Rearrange: P = nRT/V.','P = (0.20)(8.314)(300)/(0.0050) ≈ 9.98 × 10⁴ Pa.','The result is about 100 kPa absolute pressure.'),w('A sealed rigid gas starts at 100 kPa and 300 K. What is pressure at 360 K?','n and V are fixed, so P₂/P₁ = T₂/T₁.','P₂ = 100(360/300) = 120 kPa.')],
 'A flexible balloon does not generally have constant volume; a leaking container does not have a fixed gas amount.',
 [c('At fixed temperature and gas amount, volume doubles. What happens to pressure?','Pressure halves because PV is constant.','Use a ratio, not arbitrary numbers.'),c('A gas has 30 kPa gauge pressure in 100 kPa surroundings. Which pressure enters PV = nRT?','130 kPa absolute pressure.','The ideal gas law measures pressure from vacuum.')], 'thermal','Use the volume control while holding temperature fixed. Pressure changes inversely with volume.'),
 lesson('9.3','Thermal Energy Transfer and Equilibrium','Distinguish heat from internal energy and identify thermal equilibrium.',[
 ['Heat Q','Energy transferred because of a temperature difference; measured in joules, not stored as a substance.'],['Thermal equilibrium','A state with no net heat transfer between bodies in thermal contact.'],['Conduction','Energy transfer through microscopic interactions within or between matter.'],['Convection','Energy transfer by bulk movement of a fluid.'],['Radiation','Energy transfer by electromagnetic waves; it can cross a vacuum.']],
 ['Q_hot + Q_cold = 0 (isolated two-body system)','T_hot = T_cold at thermal equilibrium'],[
 s('Energy moves; temperature is a state','Heat flows spontaneously from higher temperature to lower temperature. The direction depends on temperature, not total internal energy. A large cool ocean may store more energy than a hot cup, yet it can still receive heat from the cup.'),
 s('Mechanisms in an aerospace setting','A metal support conducts energy, circulating coolant transports energy by convection, and a spacecraft radiates energy to space. Radiation is essential in a vacuum because no surrounding fluid exists for convection. Several mechanisms can act at once.'),
 s('Design an equilibrium experiment','Place measured masses at known initial temperatures in an insulated calorimeter and record temperature until it stabilizes. Include the calorimeter heat capacity if it is significant. Insulation reduces energy loss; repeat trials, use the same thermometer calibration, and discuss uncertainty. Equal final temperatures do not imply equal energy changes per kilogram.')],
 [w('An insulated system transfers 240 J from hot object A to cool object B. What are Q_A and Q_B?','Choose heat entering an object as positive.','Q_A = −240 J and Q_B = +240 J.','Total transferred heat sums to zero; neither energy nor heat has been created.'),w('Why can a satellite cool even in empty space?','Convection requires matter to move.','The satellite emits electromagnetic radiation, carrying energy away through the vacuum.')],
 'Objects in thermal equilibrium can have different internal energies; metal feeling colder than wood does not prove a lower temperature.',
 [c('Two objects at the same temperature touch. Is heat exchanged in a preferred direction?','There is no net heat transfer due to a temperature difference; microscopic exchanges may still occur.','Focus on net transfer.'),c('Which mechanism can move energy across a vacuum?','Radiation. Conduction and convection require matter.','Think about the Sun heating Earth.')], 'thermal','The explorer displays equilibrium states, not a time simulation of heating. Identify which transfer mechanism could produce the temperature change.'),
 lesson('9.4','The First Law of Thermodynamics','Track heat, work, and internal energy with a consistent sign convention.',[
 ['Work by the gas W_by','Energy transferred out by an expanding gas pushing its boundary. Compression makes W_by negative.'],['Isochoric','A process at fixed volume; boundary work is zero.'],['Isothermal','A process at fixed temperature. For an ideal gas, its internal energy does not change.'],['Adiabatic','A process with no heat transfer, Q = 0; temperature can change.']],
 ['ΔU = Q − W_by = Q + W_on','W_by = ∫ P dV (quasi-static process)','W_by = PΔV (constant pressure)','ΔU = (3/2)nRΔT (monatomic ideal gas)'],[
 s('Draw the system boundary','Choose the gas as the system. Q is positive when heat enters it. W_by is positive when the gas expands and transfers energy out. If you use work done on the gas instead, W_on = −W_by. Both conventions give the same prediction when used consistently.'),
 s('Read the P–V diagram','For a quasi-static process, the area under its P–V path equals work done by the gas. Moving right means expansion and positive work; moving left means compression and negative work. Work depends on the path between states. Internal-energy change depends only on the starting and ending states.'),
 s('Compare special processes','At fixed volume, Q = ΔU. For an isothermal ideal gas, ΔU = 0 and Q = W_by. During adiabatic expansion against an external pressure, Q = 0 and positive W_by lowers internal energy, so the ideal gas cools. In free expansion into a vacuum, W_by = 0 instead; an ideal gas does not cool. Over a complete cycle ΔU = 0 and net heat equals net work; a clockwise P–V loop has positive net work by the gas.')],
 [w('A monatomic ideal gas absorbs 750 J and expands at 100 kPa from 0.002 to 0.005 m³. Find ΔU.','W_by = PΔV = 100,000(0.003) = 300 J.','ΔU = 750 − 300 = 450 J.','More energy entered as heat than left as work, so internal energy increases.'),w('An insulated gas is compressed with 80 J of work done on it. Find ΔU.','Insulated implies Q ≈ 0. W_on = +80 J.','ΔU = Q + W_on = +80 J, so an ideal gas warms.')],
 'Adiabatic does not mean constant temperature. Never insert positive compression work into the work-by convention.',
 [c('An ideal gas expands isothermally and does 120 J of work. Find heat entering it.','Q = +120 J because ΔU = 0.','Apply the first law.'),c('Two different paths link the same initial and final equilibrium states. Which is necessarily equal: Q, W, or ΔU?','ΔU is equal. Q and W can differ while their difference remains the same.','Internal energy is a state function.')], 'thermal','Read the P–V axes. A constant-pressure expansion gives rectangular work PΔV; the state controls alone do not define a unique path.'),
 lesson('9.5','Specific Heat and Thermal Conductivity','Calculate heating, phase-change energy, and steady conduction.',[
 ['Specific heat c','Energy per unit mass per kelvin required for a temperature change; units J/(kg·K).'],['Latent heat L','Energy per unit mass for a phase change at its transition temperature; units J/kg.'],['Thermal conductivity κ','A material property controlling conduction; units W/(m·K).'],['Thermal power','Rate of energy transfer, measured in watts (J/s).']],
 ['Q = mcΔT (no phase change)','Q = +mL (melting/vaporizing); Q = −mL (freezing/condensing)','P_thermal = κA(T_hot − T_cold)/d (steady conduction)'],[
 s('Separate warming from melting','Within one phase with approximately constant specific heat, energy changes temperature by Q = mcΔT. During a phase change at fixed pressure, energy changes molecular arrangement while temperature remains at the transition value. Split a process that crosses a phase boundary into separate warming and phase-change steps.'),
 s('Find an equilibrium temperature','For an isolated mixture without phase change, sum mc(T_final − T_initial) over all components and set it to zero. Include container energy when needed. The final temperature is a heat-capacity-weighted average, not generally the arithmetic average of initial temperatures.'),
 s('Measure a transfer rate','For steady conduction through a uniform slab, rate increases with conductivity, cross-sectional area, and temperature difference, and decreases with thickness d. Assume approximately constant material properties and negligible side losses. A rate in watts multiplied by time gives transferred energy in joules.')],
 [w('How much energy warms 0.20 kg of water by 15 K? Use c = 4,180 J/(kg·K).','Q = mcΔT = 0.20 × 4,180 × 15.','Q = 12,540 J ≈ 12.5 kJ. A 15 K temperature difference is also 15 °C.'),w('A slab has κ = 0.20 W/(m·K), A = 2.0 m², d = 0.040 m, and ΔT = 10 K. Find heat-transfer rate.','P = κAΔT/d = 0.20 × 2.0 × 10 / 0.040.','P = 100 W. In 60 s, this transfers 6,000 J if the temperature difference stays fixed.')],
 'Specific heat and conductivity are different properties. A material can store substantial energy without conducting it quickly.',
 [c('Thickness doubles while other slab conditions stay fixed. What happens to conduction rate?','It halves. Rate is inversely proportional to thickness.','Inspect the denominator.'),c('Why does melting ice stay at its melting temperature while receiving energy?','Energy changes the phase and microscopic arrangement rather than increasing temperature during the phase change.','Use latent heat, not mcΔT.')], 'thermal','Temperature controls here do not include a phase change. Use a separate heating-curve sketch to show plateaus for melting or boiling.'),
 lesson('9.6','Entropy and the Second Law of Thermodynamics','Use entropy and heat-engine limits to explain the direction of processes.',[
 ['Entropy S','A state quantity measuring energy dispersal and the number of accessible microscopic arrangements; units J/K.'],['Reservoir','A body large enough to transfer heat with negligible temperature change.'],['Heat engine','A cyclic device absorbing heat, doing net work, and rejecting some heat.'],['Reversible process','An ideal limiting process that produces no net entropy increase in system plus surroundings.'],['Thermal efficiency η','Fraction of heat absorbed from the hot reservoir converted to net work per cycle: η = W_net/Q_H.']],
 ['ΔS_total ≥ 0 (qualitative second-law statement)','Optional extension: ΔS = Q_rev/T (isothermal reversible transfer)','Optional extension: η_Carnot = 1 − T_C/T_H (T_C: cold reservoir; T_H: hot reservoir; both in kelvin)'],[
 s('Conservation is necessary but not sufficient','The first law allows energy balances for processes that never occur spontaneously. The second law adds a direction: total entropy of a system plus its surroundings cannot decrease. A subsystem can lose entropy if the surroundings gain at least as much. Entropy is a state function; an isolated system tends toward maximum entropy at thermodynamic equilibrium. AP Physics 2 requires qualitative second-law reasoning; the numerical entropy and Carnot material below is optional enrichment.'),
 s('Optional extension: account for both reservoirs','If heat Q moves from a hot reservoir at T_H to a cold one at T_C, entropy changes are −Q/T_H and +Q/T_C. Their sum is positive for T_H > T_C. The reversible-transfer expression is a method of calculating state changes; it does not imply a real rapid transfer is reversible.'),
 s('Engine limits','A cyclic engine returns to its starting internal energy, so W_net = Q_H − Q_C, with heat magnitudes positive here. A reversible Carnot engine is the maximum-efficiency engine between two reservoirs. Real engines have lower efficiency. A refrigerator requires work to transfer heat from cold to hot; it does not violate the second law when the surroundings are included.')],
 [w('An engine absorbs 800 J and rejects 500 J each cycle. Find work and efficiency.','W_net = 800 − 500 = 300 J.','η = 300/800 = 0.375 = 37.5%.','Rejected heat is needed for a cyclic engine operating between finite-temperature reservoirs.'),w('Optional extension: find the maximum efficiency between 600 K and 300 K.','η_Carnot = 1 − 300/600 = 0.50 = 50%.','A real engine cannot exceed this limit for those reservoirs.')],
 'Do not use Celsius in efficiency ratios or claim that entropy must increase in every individual object.',
 [c('Heat flows spontaneously from a hot body to a cold one in an isolated system. What happens to total entropy?','It increases until thermal equilibrium is reached. The hot body can lose entropy while the combined system gains entropy.','Include both bodies.'),c('Can an isolated system spontaneously move away from equilibrium toward a lower-entropy state?','No. Its total entropy cannot decrease; equilibrium corresponds to maximum entropy under its constraints.','Apply the second law to the whole system.')], 'thermal','Use temperatures in kelvin. This explorer illustrates gas states; entropy depends on the complete change, and engine efficiency needs two reservoirs.')
];
const motion: Lesson[] = [
 lesson('1.1','Scalars and Vectors','Resolve, add, and interpret vectors using components in up to three dimensions.',[
 ['Scalar','A quantity specified by magnitude alone, such as mass or elapsed time.'],['Vector','A quantity with magnitude and direction, such as displacement or velocity.'],['Component','A signed projection of a vector onto a chosen coordinate axis.'],['Unit vector','A dimensionless vector of magnitude one indicating an axis direction: î, ĵ, or k̂.']],
 ['A⃗ = A_x î + A_y ĵ + A_z k̂','|A⃗| = √(A_x² + A_y² + A_z²)','A_x = A cos θ; A_y = A sin θ (θ from +x)'],[
 s('Choose axes before signs','A vector is independent of the coordinate system used to describe it, but its components change when the axes change. Negative components specify direction along a chosen axis, not a negative magnitude. Give each axis, its positive direction, and the origin in a sketch.'),
 s('Add components, not magnitudes','Vector addition adds corresponding components. For A⃗ + B⃗, add x to x, y to y, and z to z, then calculate the resultant magnitude. A tip-to-tail diagram is useful for reasoning, but the calculation should use components. Subtraction is addition of the opposite vector.'),
 s('Angles and calculus','Use sine and cosine based on the angle shown, not a memorized assignment. The arctangent of A_y/A_x alone can miss the quadrant; use component signs to identify the direction. Derivatives and integrals of a vector act on each component independently; this is the bridge to calculus kinematics.')],
 [w('Add A⃗ = (3î + 4ĵ) m to B⃗ = (−1î + 2ĵ) m.','R_x = 3 − 1 = 2 m; R_y = 4 + 2 = 6 m.','R⃗ = (2î + 6ĵ) m. |R⃗| = √40 ≈ 6.32 m.','θ = arctan(6/2) ≈ 71.6° above +x, in the first quadrant.'),w('Find the magnitude of (2î − 3ĵ + 6k̂) m/s.','|v⃗| = √(4 + 9 + 36) = 7 m/s.','The speed is positive even though the y component is negative.')],
 'Distance is a scalar path length. Displacement is a vector from start to finish; they agree in magnitude only for a straight path without reversal.',
 [c('Can two nonzero displacement vectors add to zero?','Yes, if they have equal magnitudes and opposite directions.','Compare each component.'),c('A vector points into quadrant II. What are its x and y component signs?','x is negative and y is positive.','Read the chosen axes.')], 'motion','The explorer plots x(t), a single component. In 2D or 3D, use a separate component function for each axis.'),
 lesson('1.2','Displacement, Velocity, and Acceleration','Differentiate and integrate motion functions with initial conditions.',[
 ['Position x(t)','Coordinate of an object relative to an origin at time t.'],['Instantaneous velocity','Time derivative of position; a signed component in 1D.'],['Instantaneous acceleration','Time derivative of velocity, or second derivative of position.'],['Initial condition','A known value such as x(0) or v(0), needed to determine an integration constant.']],
 ['v_x = v₀x + a_x t (constant a_x)', 'Δx = v₀x t + ½a_x t² (constant a_x)', 'v_x² = v₀x² + 2a_xΔx (constant a_x)', 'v_x = dx/dt; a_x = dv_x/dt = d²x/dt²','Δx = ∫ v_x dt; Δv_x = ∫ a_x dt','v_x(t) = v_x(0) + ∫₀ᵗ a_x(τ)dτ'],[
 s('Average versus instantaneous','Average velocity is Δx/Δt over an interval. Instantaneous velocity is the limit as that interval shrinks: the derivative. Average acceleration is Δv/Δt. At a turning point velocity can be zero while acceleration is nonzero.'),
 s('Recover functions by integration','Integrating acceleration gives a velocity change, not absolute velocity unless an initial value is included. Integrating velocity gives displacement. Add the initial position to find final position. Definite integrals include their bounds explicitly; indefinite integrals require constants determined by initial conditions.'),
 s('Interpret signs','Speed increases when velocity and acceleration have the same sign and decreases when their signs differ. A negative acceleration does not always mean slowing down. Integrating a constant a_x gives v_x = v₀x + a_x t. Integrating again gives Δx = v₀x t + ½a_x t². Eliminating t gives v_x² = v₀x² + 2a_xΔx. For variable acceleration these equations generally do not apply; use calculus or graph area. Near Earth, free fall has a_y = −g with upward positive and negligible drag.')],
 [w('x(t) = (2 m/s³)t³ − (3 m/s)t + 4 m. Find v and a at t = 2 s.','Differentiate: v = (6 m/s³)t² − 3 m/s. Differentiate again: a = (12 m/s³)t.','At 2 s, v = 21 m/s and a = 24 m/s².','Both are positive, so the object is speeding up then.'),w('a(t) = (4 m/s³)t and v(0) = −2 m/s. Find v(3 s).','Integrate from 0 to t: v(t) = −2 m/s + (2 m/s³)t².','v(3 s) = −2 + 18 = 16 m/s. The initial velocity must not be omitted.')],
 'A derivative needs dimensions: coefficients in x(t) carry units so every position term is in metres.',
 [c('For x(t) = (5 m/s²)t², find velocity at 2 s.','v(t) = (10 m/s²)t, so v(2 s) = 20 m/s.','Use the derivative, not x/t.'),c('An object has v = −4 m/s and a = +2 m/s². Is it speeding up?','It is slowing down at that instant because velocity and acceleration oppose each other.','Compare signs.')], 'motion','Change the acceleration and initial velocity. The plotted parabola is a constant-acceleration special case; variable acceleration needs the integral shown above.'),
 lesson('1.3','Representing Motion','Translate motion functions into graphs, slopes, and signed areas.',[
 ['Tangent slope','Instantaneous rate of change at a point on a graph.'],['Signed area','An integral counting area above the axis positive and below it negative.'],['Motion diagram','Positions at equal time intervals, optionally with velocity and acceleration vectors.'],['Distance travelled','The integral of speed, ∫|v|dt, in 1D.']],
 ['slope of x–t = v_x; slope of v_x–t = a_x','area under v_x–t = Δx; area under a_x–t = Δv_x','distance = ∫ |v_x|dt'],[
 s('Use axes to interpret a graph','A graph is not a drawing of the path. On position versus time, vertical value is position and slope is velocity. Concavity reflects acceleration. On velocity versus time, vertical value is velocity, slope is acceleration, and signed area is displacement. On acceleration versus time, signed area is velocity change.'),
 s('Handle sign changes explicitly','Displacement can cancel when motion reverses; distance cannot. Split a distance integral at the times when velocity changes sign. Acceleration being zero at a moment means the v–t tangent is horizontal, not that the object is stopped.'),
 s('Design and analyze a motion experiment','Record positions at equal time intervals with a motion sensor or calibrated video. Estimate velocities using local differences, then plot v against t. For constant acceleration, a straight-line fit to v(t) gives acceleration and initial velocity. Report units, calibration, measurement uncertainty, and why fitting multiple points is more reliable than a single pair.')],
 [w('v(t) = 4 m/s − (2 m/s²)t from t = 0 to 4 s. Find displacement and distance.','Velocity crosses zero at t = 2 s.','Displacement = ∫₀⁴(4 − 2t)dt = [4t − t²]₀⁴ = 0 m.','Distance is 4 m from 0–2 s plus 4 m from 2–4 s, for 8 m total.'),w('An x–t graph has a horizontal tangent at a smooth local maximum. What does this mean?','Velocity is zero there.','If it is concave downward, acceleration is negative. The object turns from positive to negative motion.')],
 'A decreasing position curve indicates negative velocity. Only a decreasing velocity curve indicates negative acceleration.',
 [c('A horizontal v–t line is at +3 m/s for 5 s. Find acceleration and displacement.','Acceleration is 0; displacement is +15 m.','Use slope and area separately.'),c('a(t) = (2 m/s³)t for 0–3 s. Find the velocity change.','Δv = ∫₀³2t dt = 9 m/s.','The triangular area has units of velocity.')], 'motion','The curve is a position–time graph with labelled axes. Describe its slope and concavity before checking the displayed velocity.'),
 lesson('1.4','Reference Frames and Relative Motion','Transform positions and velocities between inertial frames.',[
 ['Reference frame','Coordinates and a clock used by an observer to describe events.'],['Inertial frame','A frame in which a free particle moves with constant velocity.'],['Relative velocity','Velocity of an object as measured in a specified observer’s frame.'],['Galilean transformation','Classical frame relation using the same elapsed time for observers moving at nonrelativistic speeds.']],
 ['r⃗_A/C = r⃗_A/B + r⃗_B/C','v⃗_A/C = v⃗_A/B + v⃗_B/C','x′ = x − ut; v′ = v − u; a′ = a (constant u)'],[
 s('Name all three objects','Use a subscript A/B to mean object A relative to frame B. If a drone moves relative to air and air moves relative to ground, add drone/air and air/ground vectors to find drone/ground. Signs and components must use the same coordinate axes.'),
 s('What changes between frames','For frames with constant relative velocity u, positions and velocities differ but acceleration is the same. If the relative frame accelerates, acceleration no longer stays the same. Classical transformations are appropriate when speeds are much smaller than the speed of light.'),
 s('Plan a crossing','For a river or wind problem, time to cross depends on the component toward the opposite bank, while drift depends on the current component. A shortest-time heading and a zero-drift heading are generally different choices. Draw both frame velocities before solving.')],
 [w('A drone flies 8 m/s east relative to air; wind blows 3 m/s west relative to ground. Find ground velocity.','Take east positive. v_drone/ground = +8 + (−3).','The velocity is 5 m/s east. The wind does not subtract from every drone direction; vector addition determines the result.'),w('A boat moves 4 m/s north relative to water; current is 3 m/s east. Find ground speed and drift while crossing 40 m.','Ground velocity = (3î + 4ĵ) m/s; speed = 5 m/s.','Crossing time = 40/4 = 10 s. East drift = 3 × 10 = 30 m.')],
 '“Velocity” without an observer can be ambiguous. Use the frame labels in equations and the final sentence.',
 [c('A train moves east at 20 m/s. A passenger walks east at 1 m/s relative to it. Find passenger velocity relative to ground.','21 m/s east.','Add velocities relative to the connecting frame.'),c('Two frames move at constant relative velocity. Do they measure the same acceleration?','Yes, in the classical model, because differentiating the constant velocity difference gives zero.','Differentiate the transformation.')], 'motion','Imagine the same curve from a frame translating at constant velocity u. Subtract u from velocity; acceleration stays unchanged.'),
 lesson('1.5','Motion in Two or Three Dimensions','Apply component calculus to projectile and spatial motion.',[
 ['Position vector r⃗(t)','Vector locating a particle: x(t)î + y(t)ĵ + z(t)k̂.'],['Projectile','An object moving under gravity alone after launch in the ideal model.'],['Independent components','Component equations sharing time but evolving according to their own acceleration components.'],['Trajectory','The spatial path, distinct from a coordinate plotted against time.']],
 ['v⃗ = dr⃗/dt; a⃗ = dv⃗/dt','x = x₀ + v₀x t; y = y₀ + v₀y t − ½gt²','v_x = v₀x; v_y = v₀y − gt','g ≈ 9.8 m/s² near Earth'],[
 s('Differentiate each component','In 3D, differentiate x, y, and z separately. Speed is the magnitude of the velocity vector, not a sum of component speeds. A change in direction is a change in velocity even when speed stays constant.'),
 s('Projectile assumptions','Near Earth with negligible air resistance and constant gravitational field, choose +y upward. Acceleration is (0, −g) in 2D; horizontal velocity stays constant while vertical velocity changes. At the highest point only the vertical velocity is zero. The acceleration is still downward.'),
 s('Solve with the common time','Resolve launch velocity using v₀x = v₀ cosθ and v₀y = v₀ sinθ when θ is measured from horizontal. Solve vertical motion for the physically valid flight time, then use it in horizontal motion. The familiar range v₀² sin(2θ)/g requires equal launch and landing heights; do not use it for a launch from a cliff.')],
 [w('A ball launches horizontally at 6 m/s from 4.9 m above level ground. Find flight time and range.','Vertical: 0 = 4.9 − 4.9t², so t = 1.0 s.','Horizontal: Δx = 6(1.0) = 6.0 m.','On impact v_y = −9.8 m/s; speed = √(6² + 9.8²) ≈ 11.5 m/s.'),w('r⃗(t) = (1 m/s²)t²î + (3 m/s)tĵ − (2 m/s²)t²k̂. Find speed at 1 s.','v⃗(t) = (2 m/s²)tî + (3 m/s)ĵ − (4 m/s²)tk̂.','At 1 s, |v⃗| = √(4 + 9 + 16) = √29 ≈ 5.39 m/s.','a⃗ = (2î − 4k̂) m/s²; y acceleration is zero.')],
 'At a projectile’s apex the entire velocity is zero only for a purely vertical launch. A curved trajectory does not imply a curved force.',
 [c('At the apex of an oblique projectile, what are v_y and a_y?','v_y = 0 and a_y = −g with upward positive. Horizontal velocity remains nonzero.','Velocity and acceleration are different quantities.'),c('Two balls leave the same height at the same time with equal initial vertical velocity but different horizontal speeds. Which lands first?','They land together in the ideal model because their vertical motions are identical.','Assume negligible air resistance and the same landing level.')], 'motion','The lab plots one position component versus time. It is not a projectile trajectory: combine x(t) and y(t) to draw the actual spatial path.')
];
const field: Lesson[] = [
 lesson('8.1','Electric Charge and Electric Force','Calculate Coulomb forces and combine them as vectors.',[
 ['Electric charge q','A signed conserved property measured in coulombs (C); electron charge is −e.'],['Elementary charge e','Magnitude 1.602 × 10⁻¹⁹ C; ordinary isolated net charges are integer multiples of e.'],['Coulomb constant k','1/(4πε₀) ≈ 8.99 × 10⁹ N·m²/C² in vacuum.'],['Superposition','The total force is the vector sum of forces from individual source charges.']],
 ['F = k|q₁q₂|/r²','F⃗_net = Σ F⃗_i','q = ne (integer n)'],[
 s('Start with direction','Like charges repel and opposite charges attract. Draw the force on the selected charge along the line between the charges. The two interaction forces are equal and opposite even when charge magnitudes or masses differ. Magnitude alone does not specify a vector force.'),
 s('Separate multiple sources','Calculate each source contribution using its own separation and direction, then add components. Charge signs determine attraction or repulsion; do not combine a signed magnitude with an independently assigned direction twice. The inverse-square model is for point charges, or distributions for which equivalent spherical symmetry is justified.'),
 s('Scaling and experiments','Doubling one charge doubles its force contribution. Doubling separation reduces it to one quarter. To test the distance dependence, control charge and geometry and plot F versus 1/r²; a straight line supports the model. Stray charge, charge leakage, and finite object size can affect results.')],
 [w('Two +2.0 μC point charges are separated by 0.30 m. Find force magnitude.','Convert: 2.0 μC = 2.0 × 10⁻⁶ C.','F = 8.99 × 10⁹(2.0 × 10⁻⁶)²/(0.30)² ≈ 0.400 N.','The force is repulsive; on the right-hand charge it points right.'),w('A +q charge at the origin has identical +Q sources at x = +a and x = −a. Find net force.','Each force has magnitude kqQ/a².','The right source pushes left and the left source pushes right. Equal opposite contributions cancel.')],
 'Equal and opposite interaction forces act on different objects. They do not cancel in the free-body diagram of one object.',
 [c('Separation triples with fixed charges. How does force magnitude change?','It becomes one ninth as large.','Use the inverse square.'),c('Charge A is twice charge B. Is force on A twice force on B?','No. Their interaction forces have equal magnitude and opposite direction by Newton’s third law.','Compare the two-object interaction.')], 'field','The explorer shows field from a positive source, not force on a specified test charge. Force direction also depends on the test charge sign.'),
 lesson('8.2','Conservation of Electric Charge and the Process of Charging','Explain contact, induction, polarization, and charge conservation.',[
 ['Conductor','Material with mobile charges able to redistribute.'],['Insulator','Material whose charges are relatively bound; local polarization is possible.'],['Polarization','Separation or alignment of positive and negative charge within a neutral object.'],['Grounding','Connecting a conductor to Earth so electrons can flow to or from it.']],
 ['Σq_initial = Σq_final (isolated system)','q_net = N_protons e − N_electrons e'],[
 s('Transfer does not create charge','Charging by rubbing or contact commonly transfers electrons between materials. The total charge of an isolated pair stays the same. A positively charged ordinary object has an electron deficit; it has not generally gained mobile protons.'),
 s('Conductors and insulators','In a conductor, electrons can move throughout the object. In an insulator they are not free to move through the bulk, but bound charge can shift locally. A neutral object can be attracted to a charged one because opposite induced charge is closer than like induced charge. Attraction alone does not prove an object has nonzero net charge.'),
 s('Charging by induction','Bring a charged rod near a neutral conductor without touching it. While the rod remains nearby, connect the conductor to ground so electrons can transfer. Disconnect the ground first, then remove the rod. A positive rod draws electrons in and leaves the conductor negative; reversing the rod reverses the outcome. Include Earth in the conservation boundary because grounding makes the conductor an open system.')],
 [w('A neutral object loses 5.0 × 10⁹ electrons. Find its charge.','Losing electrons leaves positive net charge.','q = (5.0 × 10⁹)(1.602 × 10⁻¹⁹) = +8.01 × 10⁻¹⁰ C.'),w('Two identical isolated conducting spheres touch. Initial charges are +6 nC and −2 nC. Find final charges.','Total charge is +4 nC.','Identical spheres in symmetric surroundings share equally: +2 nC each.','Different shapes or surroundings do not generally share equally.')],
 'Removing the inducing rod before disconnecting ground can undo induction charging. Label the sequence explicitly.',
 [c('A charged rod attracts neutral paper. Must paper gain net charge?','No. Polarization can produce attraction without a change in net charge.','Separate charge redistribution from transfer.'),c('A positive rod charges a conductor by induction with grounding. What final sign results?','Negative, if the ground is removed before the rod. Electrons enter from Earth.','Track the mobile electrons.')], 'field','The lab assumes a fixed point source. It does not simulate mobile charge redistribution; use the induction sequence above for conductors.'),
 lesson('8.3','Electric Fields','Represent fields and connect them to forces on test charges.',[
 ['Electric field E⃗','Force per unit positive test charge at a point; units N/C.'],['Test charge','A sufficiently small probe charge that does not significantly alter the source distribution.'],['Field line','A representation whose tangent indicates E⃗ direction; density qualitatively indicates strength.'],['Uniform field','A field with the same magnitude and direction across the region considered.']],
 ['E⃗ = F⃗/q_test; F⃗ = q_test E⃗','E = k|Q|/r² (point source)','E⃗_net = Σ E⃗_i'],[
 s('A field belongs to a location','A source charge creates an electric field whether or not a test charge is present. The field at a location is defined by the force that a positive test charge would feel divided by its charge. Negative test charges feel force opposite the field. Do not include a charge’s own field when finding the external force on it.'),
 s('Draw field lines honestly','Lines point outward from positive charges and inward toward negative charges. They do not intersect: the field at a point has one direction. Field lines are not generally the paths of moving particles; trajectories also depend on initial velocity. Draw arrows small enough to preserve the line and avoid giving the impression of discrete rays.'),
 s('Use superposition','Add electric-field components from each source at the observation point. At a midpoint, equal like charges give cancelling fields, whereas equal opposite charges give fields in the same direction. Fields are vectors; a scalar sum of magnitudes is only valid for contributions already known to point the same way. At electrostatic equilibrium a conductor has zero field in its bulk and field just outside is perpendicular to its surface; otherwise charges would keep moving. An insulator can sustain a nonzero internal electric field.')],
 [w('Find field 0.20 m from a +3.0 nC point charge.','E = kQ/r² = 8.99 × 10⁹ × 3.0 × 10⁻⁹ / 0.040.','E ≈ 674 N/C directed radially outward.'),w('An electron is placed in a 200 N/C field pointing right. Find electric force.','F⃗ = qE⃗; q = −1.602 × 10⁻¹⁹ C.','Force magnitude = 3.20 × 10⁻¹⁷ N, pointing left.')],
 'Field direction is defined for a positive probe; do not reverse the field just because the actual probe is negative.',
 [c('If test charge doubles, does the source field double?','No. For a non-disturbing probe, force doubles but F/q and the source field stay the same.','Distinguish source from probe.'),c('At the midpoint between equal +Q and −Q charges, is the net field zero?','No. Both fields point from +Q toward −Q, so they add.','Draw each contribution separately.')], 'field','Change source strength and observation distance. The field arrows point outward for the positive source and the readout follows 1/r².'),
 lesson('8.4','Electric Fields of Charge Distributions','Integrate vector field contributions from continuous charge.',[
 ['Linear density λ','Charge per length, in C/m; dq = λ dl.'],['Surface density σ','Charge per area, in C/m²; dq = σ dA.'],['Volume density ρ','Charge per volume, in C/m³; dq = ρ dV.'],['Symmetry','A property allowing equivalent contributions to cancel or combine.']],
 ['dE⃗ = k(dq/r²) r̂ (r̂ points from source element to observation point)','E⃗ = ∫ dE⃗','E_z,ring = kQz/(z² + a²)^(3/2) (a: ring radius; z: signed axial coordinate)'],[
 s('Build the integral from geometry','Choose a small charge element dq, write its separation vector to the observation point, and project dE⃗ onto each axis before integrating. If density varies, keep it inside the integral. State integration limits and which components cancel by symmetry. The distance r is not automatically the integration coordinate.'),
 s('A uniformly charged ring','For a ring of radius a, every element is √(a²+z²) from a point on its axis. Transverse contributions cancel in pairs. The surviving axial projection adds a factor z/√(a²+z²), giving E_z = kQz/(a²+z²)^(3/2). At the centre z = 0 the field is zero. Far away it approaches the point-charge field.'),
 s('Rods, arcs, and disks','For a straight rod, select position x along the rod and write dq = λ dx, with distance and projection determined from the observation point. For an arc, dq = λa dθ and use sine/cosine projections. As optional enrichment beyond the required AP distributions, a disk can be stacked from rings with dq = σ2πa da. Integrating magnitudes first can miss cancellations; include vectors from the beginning.')],
 [w('Find the field at the centre of a uniform positive semicircular arc of radius a and total charge Q above the x axis.','Let θ run 0 to π and λ = Q/(πa). Fields point away from each source toward the centre.','dE_y = −kλ sinθ dθ/a; x components cancel.','E_y = −(kλ/a)∫₀^π sinθ dθ = −2kQ/(πa²). It points downward.'),w('For a uniform rod from −L/2 to +L/2, find the field at (0,y), y > 0.','Horizontal components cancel. dq = λdx and r = √(x²+y²).','Eᵧ = kλ ∫ [y/(x² + y²)^(3/2)] dx, with limits x = −L/2 to +L/2. Evaluating gives Eᵧ = kλL/[y√(y² + (L/2)²)].','It points along +y for positive λ. Far away, E ≈ kλL/y², as expected for total charge Q = λL.'),w('For a uniformly charged ring, explain the large-z limit of its axial field.','If z ≫ a, (z²+a²)^(3/2) ≈ z³ for z positive.','E_z ≈ kQz/z³ = kQ/z², matching a point charge.')],
 'dq and r vary differently. Define both from the sketch before selecting the integration variable.',
 [c('A uniform charged ring has nonzero Q. Why is its centre field zero?','Each field contribution is cancelled by the diametrically opposite one. Nonzero charge does not guarantee nonzero field at every point.','Use vector symmetry.'),c('For a straight rod with linear charge density λ, what is dq for a small length dx?','dq = λ dx. Charge equals linear density times length.','Check that the result has units of coulombs.')], 'field','The lab is a point-source model. A ring or rod requires the integral in this lesson; the point-source model is only a far-field approximation.'),
 lesson('8.5','Electric Flux','Compute field flow through surfaces with area normals.',[
 ['Electric flux Φ_E','Surface integral of the field’s normal component; units N·m²/C.'],['Area vector dA⃗','A vector perpendicular to a surface element with magnitude equal to its area.'],['Closed surface','A surface fully enclosing a volume; normals conventionally point outward.'],['Normal angle θ','The angle between field and area normal, not between field and the plane.']],
 ['Φ_E = ∫ E⃗·dA⃗','Φ_E = EA cosθ (uniform field, flat surface)','Φ_E,closed = ∮ E⃗·dA⃗'],[
 s('Choose the normal','A flat surface has two possible normal directions; state the one used. On a closed surface choose outward normals. Flux is positive where field points outward and negative where it points inward. A field parallel to the surface gives zero flux because its normal component is zero.'),
 s('Flux is not field strength','Flux depends on field, area, and orientation together. A strong field can give zero net flux through a closed surface when equal contributions enter and leave. Net flux counts their signed sum; it does not mean the field is absent.'),
 s('Use the integral when needed','EA cosθ applies only when field and surface orientation are constant over the patch. For curved surfaces or nonuniform fields, sum or integrate local dot products. In a uniform field a closed cube has zero net flux: the entering and leaving faces cancel and parallel faces contribute zero.')],
 [w('A 300 N/C uniform field crosses a 0.020 m² flat patch at 60° to its normal. Find flux.','Φ = EA cosθ = 300 × 0.020 × cos60°.','Φ = +3.0 N·m²/C for the stated normal.'),w('A cube is in a uniform field along +x. Explain its net flux.','The +x face has flux +EA; the −x face has −EA.','The other four faces have zero dot product. Net flux is zero even though the field is nonzero.')],
 'Use the angle to the normal; an angle given relative to the plane must first be converted.',
 [c('A field lies in the plane of a flat surface. What is flux?','Zero, because the field is perpendicular to the area normal.','Compute the dot product.'),c('Does zero net flux through a closed surface imply zero field on it?','No. Inward and outward contributions may cancel.','Consider a cube in a uniform field.')], 'field','The radial field shown would have constant normal magnitude on a sphere centred on the source. For a tilted flat patch, multiply by area and cosθ.'),
 lesson('8.6','Gauss’s Law','Use enclosed charge and symmetry to calculate electric fields.',[
 ['Gaussian surface','An imaginary closed surface chosen for a flux calculation.'],['Enclosed charge Q_enc','Net charge inside that surface, excluding charges outside it.'],['Permittivity ε₀','Vacuum constant ≈ 8.85 × 10⁻¹² C²/(N·m²).'],['Electrostatic equilibrium','A state with no net motion of charge in a conductor; its interior field is zero.']],
 ['∮ E⃗·dA⃗ = Q_enc/ε₀','E_r,sphere = Q/(4πε₀r²) (outside; radial component)','E_r,line = λ/(2πε₀r) (infinite uniform line)','|E_sheet| = |σ|/(2ε₀) (infinite isolated sheet)'],[
 s('The law is always true; the shortcut is not','Gauss’s law relates net flux to enclosed charge for every closed surface. To solve for E by pulling it outside an integral, symmetry must guarantee a known direction and constant magnitude on the contributing surface. A cube around a point charge has known total flux, but field magnitude varies across each face.'),
 s('Spherical and cylindrical symmetry','For a spherical charge distribution use a concentric sphere: E4πr² = Q_enc/ε₀. For an effectively infinite uniform line use a coaxial cylinder: only its curved side contributes, so E2πrL = λL/ε₀. For a large uniform sheet use a pillbox; both caps contribute EA, giving 2EA = σA/ε₀.'),
 s('Inside distributions and conductors','Inside a uniformly charged insulating sphere of radius R, Q_enc = Qr³/R³ and E = Qr/(4πε₀R³). Inside an electrostatic conductor, E = 0 and excess charge lies on its surfaces. For variable volume density, first calculate Q_enc by integrating ρ over the enclosed volume. External charges contribute local fields but zero net flux through the surface.')],
 [w('An insulating sphere has uniform charge Q and radius R. Compare E at r = R/2 with E at the surface.','Inside: E(r) = kQr/R³.','E(R/2) = kQ/(2R²), which is one half the surface field kQ/R².','The inverse-square formula with total Q is not valid inside the sphere.'),w('An infinite insulating cylinder has uniform positive density ρ and radius R. Find E inside and outside.','Use a coaxial Gaussian cylinder of length ℓ. For r < R, Q_enc = ρπr²ℓ.','E(2πrℓ) = Q_enc/ε₀, so E_inside = ρr/(2ε₀).','For r ≥ R, Q_enc = ρπR²ℓ, so E_outside = ρR²/(2ε₀r). The field is radially outward and continuous at R.'),w('A sphere has volume charge density ρ(r) = Cr for r ≤ R, with C positive. Find the internal field.','Q_enc = ∫₀ʳ(Cs)(4πs²)ds = πCr⁴.','Gauss: E(4πr²) = πCr⁴/ε₀, so E = Cr²/(4ε₀), outward.','Do not use the total charge inside radius R for an internal Gaussian surface; only charge inside r enters.'),w('A closed surface encloses +3 nC and −1 nC. Find net flux.','Q_enc = +2 × 10⁻⁹ C.','Φ = Q_enc/ε₀ ≈ +226 N·m²/C. External charge does not change this net flux.')],
 'Q_enc = 0 implies zero net flux, not necessarily E = 0. Only appropriate symmetry justifies solving for a constant field.',
 [c('Why is an infinite line’s field proportional to 1/r rather than 1/r²?','The cylindrical surface area grows as 2πrL while enclosed charge λL stays fixed.','Use the Gaussian geometry.'),c('Is it valid to use a spherical Gaussian surface to find E from an arbitrary nearby dipole?','Its total flux is still fixed by enclosed charge, but field magnitude is not constant on the sphere, so the simple E4πr² shortcut is invalid.','Distinguish the law from the symmetry shortcut.')], 'field','For this centred point source, E4πr² is independent of radius. That spherical symmetry makes Gauss’s law useful for finding E.')
];
function unit(slug:string,title:string,apNumber:number,source:string,lessons:Lesson[],questions:Question[],freeResponse:UnitOne['freeResponse']): UnitOne {
 return {slug,title,apNumber,source,description:`First unit of this course • College Board Unit ${apNumber}. Build concepts, practise representations, and explain your reasoning.`,status:'Available',progress:`${lessons.length} of ${lessons.length} topics available`,objectives:lessons.map(l=>l.summary),lessons,practice:lessons.flatMap(l=>l.checks),testStatus:'Available',questions,freeResponse};
}
export const unitOnes: Record<string,UnitOne> = {
 'physics-2': unit('thermodynamics','Thermodynamics',9,'https://apcentral.collegeboard.org/courses/ap-physics-2',thermal,[
 q('Two ideal gases at the same temperature have different molecular masses. Their average translational kinetic energies are…',['Equal','Larger for the heavier molecules','Larger for the lighter molecules','Always zero'],0,'K_avg = (3/2)k_B T depends on temperature, not molecular mass.'),
 q('A sealed rigid container of ideal gas warms from 300 K to 450 K. Pressure changes by a factor of…',['2/3','1.5','2.25','1'],1,'At fixed N and V, pressure is proportional to absolute temperature.'),
 q('An ideal gas doubles its volume at constant temperature and amount. Its pressure…',['Doubles','Stays the same','Halves','Quadruples'],2,'PV is constant, so pressure is inversely proportional to volume.'),
 q('Which transfers thermal energy across a vacuum?',['Conduction','Convection','Radiation','Only contact'],2,'Electromagnetic radiation needs no material medium.'),
 q('A gas absorbs 700 J and does 250 J of work. ΔU equals…',['950 J','450 J','−450 J','−950 J'],1,'With work by the gas positive, ΔU = Q − W_by = 450 J.'),
 q('An ideal gas expands adiabatically and does positive work on its surroundings. Its temperature…',['Increases','Decreases','Must remain constant','Is determined by Celsius ratios'],1,'Q = 0 and positive work lowers internal energy.'),
 q('A 0.50 kg body with c = 400 J/(kg·K) warms by 10 K. Energy needed is…',['20 J','200 J','2,000 J','20,000 J'],2,'Q = mcΔT = 0.50 × 400 × 10 = 2,000 J.'),
 q('A uniform slab doubles in thickness in steady conduction, with its area and face temperatures fixed. Conduction rate…',['Halves','Doubles','Quadruples','Is unchanged'],0,'Rate is proportional to 1/d.'),
 q('An isolated thermal system approaches equilibrium. Its total entropy tends toward…',['A minimum','A maximum under its constraints','Zero in every case','The entropy of one particle'],1,'An isolated system approaches the maximum entropy permitted by its constraints.'),
 q('A local system’s entropy decreases. The second law requires…',['The process is impossible','Surroundings’ entropy always stays constant','Total entropy of system plus surroundings does not decrease','Internal energy must vanish'],2,'A subsystem can lose entropy when its surroundings gain enough to keep the total nondecreasing.'),
 q('Over one complete heat-engine cycle, its internal-energy change is…',['Positive','Negative','Zero','Equal to absorbed heat'],2,'Internal energy is a state quantity and the engine returns to its initial state.'),
 q('At a melting plateau, added energy mainly…',['Raises temperature','Changes the phase','Makes specific heat zero','Stops all molecular motion'],1,'Latent heat changes phase at its transition temperature rather than raising temperature.')
 ],[
 {prompt:'A monatomic ideal gas expands at 1.0 × 10⁵ Pa from 0.0020 to 0.0050 m³ while absorbing 750 J. Calculate work by the gas and ΔU. Explain whether its temperature rises. Then describe how a P–V graph represents the work.',rubric:['Identify expansion and positive work by the gas.','W_by = PΔV = 300 J.','ΔU = 750 − 300 = +450 J.','For fixed monatomic ideal gas, ΔU ∝ ΔT so temperature rises.','The rectangular area under the constant-pressure path is 300 J.']},
 {prompt:'Design an insulated mixing experiment to estimate the specific heat of a metal. Explain measurements, the energy-balance equation, and two sources of error.',rubric:['Measure metal and water masses and both initial temperatures.','Record their common final temperature in an insulated calorimeter.','Set m_m c_m(T_f−T_m) + m_w c_w(T_f−T_w) + C_cal(T_f−T_w) = 0.','Solve for c_m; include calorimeter capacity or justify neglecting it.','Discuss heat lost to air during transfer and thermometer or mass uncertainties; repeat trials.']}
 ]),
 'physics-c-mechanics': unit('calculus-kinematics','Kinematics',1,'https://apcentral.collegeboard.org/courses/ap-physics-c-mechanics',motion,[
 q('The magnitude of (3î − 4ĵ) m is…',['−1 m','1 m','5 m','7 m'],2,'Use the Euclidean magnitude √(3²+4²), not a sum of components.'),
 q('For x(t) = (2 m/s³)t³ − (3 m/s)t + 1 m, velocity at 2 s is…',['11 m/s','21 m/s','24 m/s','16 m/s'],1,'v(t) = (6 m/s³)t² − 3 m/s, giving 21 m/s.'),
 q('An object has negative velocity and positive acceleration. At that instant it…',['Speeds up','Slows down','Has zero speed','Has zero acceleration'],1,'Opposite signs of velocity and acceleration reduce speed.'),
 q('If a(t) = (6 m/s³)t and v(0) = 2 m/s, v(2 s) is…',['12 m/s','14 m/s','24 m/s','26 m/s'],1,'The velocity change is the integral of acceleration from 0 to 2 s: 12 m/s. Add v(0) = 2 m/s to obtain 14 m/s.'),
 q('Signed area under a velocity–time graph gives…',['Distance in all cases','Acceleration','Displacement','Position without an initial condition'],2,'Integrating velocity gives displacement. Distance uses |v|.'),
 q('v(t) = 4 m/s − (2 m/s²)t for 0–4 s. Distance travelled is…',['0 m','4 m','8 m','16 m'],2,'Split at t = 2 s; each triangular speed area is 4 m.'),
 q('At a projectile’s apex, with +y upward and nonzero horizontal speed…',['All velocity is zero','a_y = 0','v_y = 0 and a_y = −g','v_x = 0'],2,'Gravity still acts at the apex; only the vertical velocity is zero.'),
 q('A boat moves 4 m/s north relative to water and current is 3 m/s east. Ground speed is…',['1 m/s','4 m/s','5 m/s','7 m/s'],2,'Perpendicular components give √(4²+3²) = 5 m/s.'),
 q('Two classical inertial frames translate at constant relative velocity. They measure the same…',['Position','Velocity','Acceleration','Displacement for every interval'],2,'The derivative of their constant velocity difference is zero.'),
 q('A horizontal launch at 10 m/s from 19.6 m, with g = 9.8 m/s², has flight time…',['1 s','2 s','4 s','10 s'],1,'19.6 = (1/2)(9.8)t² gives t = 2 s.'),
 q('For r⃗(t) = (1 m/s²)t²î + (3 m/s)tĵ + (1 m/s³)t³k̂, acceleration at 1 s has components (in m/s²)…',['(2, 3, 3)','(2, 0, 6)','(1, 3, 1)','(0, 0, 0)'],1,'Differentiate each coordinate twice: a⃗(t) = (2 m/s²)î + (6 m/s³)tk̂.'),
 q('A horizontal tangent on x(t) tells you…',['Velocity is zero','Acceleration is zero','Position is zero','The object is permanently at rest'],0,'A tangent slope is instantaneous velocity, which can be zero just at a turn.')
 ],[
 {prompt:'A particle has v(t) = 6 m/s − (3 m/s²)t from 0 to 4 s and x(0) = 2 m. Find its turning time, final position, displacement, and distance. Describe its x–t graph.',rubric:['Set v = 0 to obtain a turn at 2 s.','Integrate: x(t) = 2 m + (6 m/s)t − (1.5 m/s²)t².','x(4) = 2 m and displacement is 0 m.','Split at the turn: 6 m outward and 6 m back give 12 m distance.','x–t is a concave-down parabola with a maximum x = 8 m at 2 s.']},
 {prompt:'A projectile launches from the ground at 20 m/s and 30° above horizontal. Neglect drag and use g = 9.8 m/s². Derive flight time and range for landing at the same height. Explain what is true at the apex.',rubric:['Resolve v₀x = 20cos30° ≈ 17.3 m/s and v₀y = 10 m/s.','Set Δy = 10t − 4.9t² = 0; nonzero time is 2.04 s.','Range = v₀x t ≈ 35.3 m.','At apex v_y = 0 while v_x remains 17.3 m/s and acceleration is downward.','Equal launch/landing heights, constant g, and negligible air resistance are required assumptions.']}
 ]),
 'physics-c-em': unit('electrostatics','Electric Charges, Fields, and Gauss’s Law',8,'https://apcentral.collegeboard.org/courses/ap-physics-c-electricity-and-magnetism',field,[
 q('Separation between fixed point charges doubles. Force becomes…',['Twice as large','Four times as large','One half as large','One quarter as large'],3,'Coulomb force is proportional to 1/r².'),
 q('An ordinary neutral object loses electrons. Its net charge becomes…',['Positive','Negative','Always zero','Undefined'],0,'Removing negative charge leaves an electron deficit and positive net charge.'),
 q('Neutral paper attracted to a charged rod demonstrates…',['Necessary net positive charge','Possible polarization','Creation of charge','Proton flow through paper'],1,'Polarization can create attraction without changing net charge.'),
 q('The field points right. Force on an electron points…',['Right','Left','Up','No direction'],1,'F⃗ = qE⃗; negative charge reverses the direction.'),
 q('At the midpoint between equal positive source charges, net electric field is…',['Zero','Always positive','Twice either field','Infinite'],0,'The equal field contributions point in opposite directions.'),
 q('A uniform positive ring produces what field at its centre?',['kQ/a²','Zero','An infinite field','A field toward the nearest point only'],1,'Opposite ring elements produce cancelling vector contributions.'),
 q('A uniform rod with linear charge density λ has charge in a small element dx equal to…',['λ/dx','λdx²','λdx','λx²'],2,'Linear density has units C/m, so dq = λdx has units of charge.'),
 q('The plane of a flat patch is parallel to a uniform field. Flux is…',['EA','−EA','EA/2','Zero'],3,'The field is perpendicular to the surface normal, so cosθ = 0.'),
 q('A charge outside a closed surface contributes what net flux through it?',['q/ε₀','Zero','Always positive flux','Infinite flux'],1,'It can change local fields, but enters and leaves with zero net flux.'),
 q('Inside a uniformly charged insulating sphere, field magnitude is proportional to…',['1/r²','1/r','r','r²'],2,'Q_enc ∝ r³ and spherical area ∝ r², giving E ∝ r.'),
 q('In an electrostatic conductor’s bulk interior, electric field is…',['Zero','Always kQ/r²','Proportional to temperature','Equal to flux'],0,'Mobile charges redistribute until the bulk field is zero at equilibrium.'),
 q('Why is Gauss’s law alone insufficient to find E at an arbitrary point near an asymmetric distribution?',['Gauss’s law fails','Flux is not defined','Symmetry may not make E constant on a useful surface','External charges never create fields'],2,'Gauss’s law remains valid, but symmetry is needed to simplify the flux integral to a known area times E.')
 ],[
 {prompt:'A nonconducting sphere of radius R has uniform charge density ρ. Derive E(r) inside and outside, including direction, and check continuity at R.',rubric:['Choose a concentric sphere and use spherical symmetry for radial E.','Inside, Q_enc = ρ(4πr³/3), so E = ρr/(3ε₀).','Outside, Q_total = ρ(4πR³/3), so E = ρR³/(3ε₀r²).','At R both expressions equal ρR/(3ε₀); field is continuous.','Direction is outward for positive ρ, inward for negative ρ.']},
 {prompt:'A uniform rod lies on the x axis from x = 0 to L and has positive density λ. At an observation point x = −a with a > 0, set up and evaluate the electric field integral. Check the far-field limit.',rubric:['Use dq = λ dx and distance a + x from each source element.','All contributions point in −x.','E_x = −kλ∫₀ᴸ dx/(a+x)².','E_x = −kλ(1/a − 1/(a+L)).','For a ≫ L, E_x ≈ −kλL/a² = −kQ/a².']}
 ])
};
export function getUnitOne(courseSlug:string,unitSlug:string) { const u=unitOnes[courseSlug]; return u?.slug===unitSlug ? u : undefined; }

// Thermodynamics follows the same full teaching sequence as the detailed Physics 1 lessons.
const thermoUnit = unitOnes['physics-2'];
thermoUnit.lessons[0].equations.push('v_rms = √(3k_B T/m)', 'U = (3/2)nRT (monatomic ideal gas)');
thermoUnit.lessons[0].terms.push(['Root-mean-square speed','Square root of the mean squared particle speed; it is not the most probable speed.'],['Maxwell–Boltzmann distribution','A distribution of particle speeds; its area represents particle count or normalized probability.']);
thermoUnit.lessons.forEach(l=>{l.estimatedTime='70–100 minutes, with practice';l.objectives=guidedLessons[l.apTopic].checklist;});
thermoUnit.questions.push(
 q('The rms speed of a fixed gas increases by a factor of 3. Its kelvin temperature increases by…',['3','√3','9','1/9'],2,'The average translational energy is proportional to the mean squared speed and to T. Thus T scales by 3² = 9.'),
 q('The normalized speed distribution of the same gas is compared at a higher temperature. Which combination is correct?',['Higher peak speed, broader curve, equal total area','Higher peak speed, narrower curve, greater total area','Lower peak speed, broader curve, equal total area','Unchanged curve'],0,'Higher T shifts characteristic speeds upward and spreads the distribution. Normalization keeps total area equal to 1.'),
 q('For 0.20 mol in a rigid 5.0 L vessel, the slope of P(kPa) versus T(K) is approximately…',['0.0033 kPa/K','0.333 kPa/K','33.3 kPa/K','333 kPa/K'],1,'P(kPa) = nR T/V(L), so slope = 0.20 × 8.314/5.0 = 0.333 kPa/K. The kPa and L conversions cancel.'),
 q('A rigid sealed vessel has initial gauge pressure 100 kPa when atmospheric pressure is 100 kPa, at 300 K. At 450 K its gauge pressure is…',['150 kPa','200 kPa','300 kPa','450 kPa'],1,'Absolute initial P is 200 kPa. Scale by 450/300 to get 300 kPa absolute, then subtract 100 kPa atmospheric pressure.'),
 q('The state data for fixed amount are A: 100 kPa, 2 L; B: 200 kPa, 4 L. T_B/T_A equals…',['1','2','4','8'],2,'T ∝ PV. The PV product grows from 200 to 800 kPa·L, a factor of 4.'),
 q('A monatomic ideal gas moves between the states A: 100 kPa, 2 L and B: 200 kPa, 4 L. Its internal-energy change is…',['200 J','600 J','900 J','1300 J'],2,'U = (3/2)PV. ΔU = (3/2)(800 − 200) = 900 J because 1 kPa·L = 1 J.'),
 q('Between those same A and B states, Path I first increases pressure at 2 L then expands at 200 kPa; Path II first expands at 100 kPa then increases pressure at 4 L. Which is correct?',['ΔU is larger on Path I','Both paths have equal work','Path I needs 200 J more heat','Path II needs 200 J more heat'],2,'Work on Path I is 400 J and on Path II 200 J; vertical legs give zero work. ΔU is identical, so Q_I − Q_II = 200 J.'),
 q('A clockwise rectangular P–V loop spans 100–300 kPa and 2–4 L. Net work by the gas is…',['−400 J','+400 J','+800 J','0 J'],1,'The clockwise sign is positive, and enclosed area is (300 − 100)(4 − 2) = 400 kPa·L = 400 J.'),
 q('In an insulated mixture, object A has heat capacity 200 J/K at 80 °C and object B 400 J/K at 20 °C. With no phase change, final temperature is…',['30 °C','40 °C','50 °C','60 °C'],1,'200(T_f − 80) + 400(T_f − 20) = 0 yields T_f = 40 °C. The answer is nearer the initial temperature of the larger heat capacity.'),
 q('A Q-versus-ΔT graph for a 0.50 kg sample has slope 1000 J/K. Its specific heat is…',['500 J/(kg·K)','1000 J/(kg·K)','2000 J/(kg·K)','5000 J/(kg·K)'],2,'The slope is mc, so c = 1000/0.50 = 2000 J/(kg·K). Reversing axes would change the slope interpretation.'),
 q('An insulated ideal gas expands freely into a vacuum. Its work by the gas and internal-energy change are…',['Both zero','Both positive','Work zero, internal energy negative','Work positive, internal energy zero'],0,'Vacuum offers zero external pressure, so W_by = 0. Insulation gives Q = 0; the first law then gives ΔU = 0.'),
 q('A proposed cyclic machine absorbs 500 J from a single reservoir and converts all of it to work with no other effect. It…',['Violates energy conservation only','Satisfies both laws','Satisfies the first-law balance but violates the second law','Must be a real reversible engine'],2,'Its energy amounts balance, but a cycle with complete heat-to-work conversion from one reservoir and no other effect violates the second law.')
);
thermoUnit.freeResponse.push(
 {prompt:'Translation between representations: A fixed amount of monatomic ideal gas goes from A (2.0 L, 100 kPa) to B (4.0 L, 200 kPa). Path I raises pressure at fixed volume, then expands at 200 kPa. Path II expands at 100 kPa, then raises pressure at fixed volume. Draw both labelled paths with arrows on common axes starting at zero pressure. Calculate T_B/T_A, ΔU, work by the gas, and heat for each path. Explain why only some quantities agree.',rubric:['State PV = nRT; fixed n gives T_B/T_A = (200×4)/(100×2) = 4.','Draw Path I through (2 L, 200 kPa) and Path II through (4 L, 100 kPa), with arrows A→B.','ΔU = (3/2)Δ(PV) = 900 J for either path.','W_by,I = 400 J; W_by,II = 200 J. Fixed-volume legs do no boundary work.','Q_I = 1300 J; Q_II = 1100 J from Q = ΔU + W_by.','State that internal energy depends on endpoints while heat and work depend on path.']},
 {prompt:'Qualitative/quantitative reasoning: Two equal-particle-count samples of the same ideal gas are at 300 K and 600 K. Sketch their normalized speed distributions on common labelled axes. Compare average translational energy and rms speed. Then consider a cyclic device claiming to take heat from one reservoir and convert it all into work with no other effect. Explain separately whether its energy accounting and its spontaneous operation are consistent with the first and second laws.',rubric:['Higher-T speed curve has peak at greater speed and is broader and lower; full normalized areas are equal.','Average translational particle energy doubles because K_avg ∝ T.','Rms speed increases by √2 because v_rms ∝ √T.','A cycle has ΔU = 0; equal input heat and output work can satisfy first-law amounts.','The claimed single-reservoir heat-to-work cycle with no other effect violates the second law; conservation alone does not establish feasibility.']}
);
